### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by shuangshuangguo** [chinancheng/awesome-activity-prediction#1]
hi, @chinancheng 
Thanks for your sharing! I'm working on early prediction problem, and I found that there are few source code to follow. So depressed.
If you have any code for prediction, can you share with us?
Thank you very much!

**Comment by chinancheng** [comment]
Hi,
Unfortunately not help, I don't have any code for early prediction problem.  If I find or implement some, I will share with you. Thanks!
